"""add_original_profile_picture

Revision ID: 41ae2c3d7c81
Revises: 53f011402e04
Create Date: 2026-05-17 03:13:44.775581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ae2c3d7c81'
down_revision: Union[str, None] = '53f011402e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_profile_picture_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('original_profile_picture_url')

    # ### end Alembic commands ###
