"""add_signup_payload_to_verification_code

Revision ID: ad9080f8c23e
Revises: 5fa481556aa7
Create Date: 2026-05-27 21:13:54.949593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9080f8c23e'
down_revision: Union[str, None] = '5fa481556aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_payload', sa.String(length=2047), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_column('signup_payload')

    # ### end Alembic commands ###
