"""add_onboarding_complete_to_user

Revision ID: 1832aaff593c
Revises: b6a44caa136c
Create Date: 2026-05-23 13:41:09.827968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1832aaff593c"
down_revision: Union[str, None] = "b6a44caa136c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "onboarding_complete", sa.Boolean(), server_default="0", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("onboarding_complete")

    # ### end Alembic commands ###
