"""add_ai_type_to_usage_logs

Revision ID: c7ff2b5f60c6
Revises: 1832aaff593c
Create Date: 2026-05-25 05:19:18.302426

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7ff2b5f60c6"
down_revision: Union[str, None] = "1832aaff593c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_usage_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ai_type", sa.String(), nullable=False, server_default="portal")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_usage_logs", schema=None) as batch_op:
        batch_op.drop_column("ai_type")

    # ### end Alembic commands ###
