"""add_assessment_methodology_to_predictions

Revision ID: a436cd6ffe0f
Revises: 444673ab0a6e
Create Date: 2026-06-02 05:53:32.525302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a436cd6ffe0f'
down_revision: Union[str, None] = '444673ab0a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_methodology', sa.String(length=20), server_default='full', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('assessment_methodology')

    # ### end Alembic commands ###
