"""add_auth_attempt_rate_limiting_to_users

Revision ID: 09fa164e2f19
Revises: a436cd6ffe0f
Create Date: 2026-06-09 07:30:06.824650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fa164e2f19'
down_revision: Union[str, None] = 'a436cd6ffe0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_attempt_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('auth_window_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('auth_locked_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_locked_until')
        batch_op.drop_column('auth_window_start')
        batch_op.drop_column('auth_attempt_count')

    # ### end Alembic commands ###
