"""add_portal_type_and_verification_code

Revision ID: 5fa481556aa7
Revises: c7ff2b5f60c6
Create Date: 2026-05-27 03:22:38.630274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5fa481556aa7"
down_revision: Union[str, None] = "c7ff2b5f60c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("portal_type", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("resend_count", sa.Integer(), nullable=False),
        sa.Column("last_resend_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "email", "portal_type", name="uq_verification_email_portal"
        ),
    )
    with op.batch_alter_table("verification_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_codes_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_verification_codes_id"), ["id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "portal_type",
                sa.String(length=20),
                server_default="sme",
                nullable=False,
            )
        )
        batch_op.drop_index("ix_users_email")
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_unique_constraint(
            "uq_user_email_portal", ["email", "portal_type"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email_portal", type_="unique")
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index("ix_users_email", ["email"], unique=1)
        batch_op.drop_column("portal_type")

    with op.batch_alter_table("verification_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_codes_id"))
        batch_op.drop_index(batch_op.f("ix_verification_codes_email"))

    op.drop_table("verification_codes")
    # ### end Alembic commands ###
