"""add_business_scale_to_user

Revision ID: b6a44caa136c
Revises: 292d5f421d1a
Create Date: 2026-05-22 04:05:14.541285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b6a44caa136c"
down_revision: Union[str, None] = "292d5f421d1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("business_scale", sa.String(length=20), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("business_scale")

    # ### end Alembic commands ###
