"""add_ai_usage_logging

Revision ID: 37af73611f18
Revises: fac939f2c3cd
Create Date: 2026-05-08 17:23:50.301794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "37af73611f18"
down_revision: Union[str, None] = "fac939f2c3cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_usage_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_usage_logs_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_usage_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_logs_id"))

    op.drop_table("ai_usage_logs")
    # ### end Alembic commands ###
