"""add_expires_at_to_user_device_sessions

Revision ID: 444673ab0a6e
Revises: e5b9f7a1c2d3
Create Date: 2026-05-30 09:15:22.068867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444673ab0a6e'
down_revision: Union[str, None] = 'e5b9f7a1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # user_agent was already added in e5b9f7a1c2d3, removing duplicate addition here.

    # Use a default value for existing rows (24 hours from now)
    from datetime import datetime, timedelta, timezone
    default_expiry = datetime.now(timezone.utc) + timedelta(days=1)

    with op.batch_alter_table('user_device_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, server_default=default_expiry.isoformat()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device_sessions', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
