"""add_user_role

Revision ID: fac939f2c3cd
Revises: 
Create Date: 2026-04-22 14:46:09.414713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac939f2c3cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='sme_owner', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('registration_number', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_owner_id'), ['owner_id'], unique=False)

    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('current_assets', sa.Float(), nullable=False),
    sa.Column('current_liabilities', sa.Float(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('total_liabilities', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('inventory', sa.Float(), nullable=False),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=False),
    sa.Column('retained_earnings', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=False),
    sa.Column('ebit', sa.Float(), nullable=False),
    sa.Column('interest_expense', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', name='uq_financial_record_company_period')
    )
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_records_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_records_id'), ['id'], unique=False)

    op.create_table('ratio_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_record_id', sa.Integer(), nullable=False),
    sa.Column('current_ratio', sa.Float(), nullable=False),
    sa.Column('quick_ratio', sa.Float(), nullable=False),
    sa.Column('cash_ratio', sa.Float(), nullable=False),
    sa.Column('debt_to_equity', sa.Float(), nullable=False),
    sa.Column('debt_to_assets', sa.Float(), nullable=False),
    sa.Column('interest_coverage', sa.Float(), nullable=False),
    sa.Column('net_profit_margin', sa.Float(), nullable=False),
    sa.Column('return_on_assets', sa.Float(), nullable=False),
    sa.Column('return_on_equity', sa.Float(), nullable=False),
    sa.Column('asset_turnover', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_record_id'], ['financial_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratio_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratio_features_financial_record_id'), ['financial_record_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ratio_features_id'), ['id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ratio_feature_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=30), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('distress_probability', sa.Float(), nullable=False),
    sa.Column('shap_values_json', sa.Text(), nullable=False),
    sa.Column('prediction_hash', sa.String(length=64), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ratio_feature_id'], ['ratio_features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ratio_feature_id', 'model_used', name='uq_prediction_ratio_feature_model')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_prediction_hash'), ['prediction_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_ratio_feature_id'), ['ratio_feature_id'], unique=False)

    op.create_table('narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('narratives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narratives_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_narratives_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narratives_prediction_id'), ['prediction_id'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_prediction_id'), ['prediction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('narratives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narratives_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_narratives_id'))
        batch_op.drop_index(batch_op.f('ix_narratives_cache_key'))

    op.drop_table('narratives')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_ratio_feature_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_prediction_hash'))
        batch_op.drop_index(batch_op.f('ix_predictions_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('ratio_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratio_features_id'))
        batch_op.drop_index(batch_op.f('ix_ratio_features_financial_record_id'))

    op.drop_table('ratio_features')
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_records_id'))
        batch_op.drop_index(batch_op.f('ix_financial_records_company_id'))

    op.drop_table('financial_records')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_owner_id'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
