"""add_session_tables

Revision ID: e5b9f7a1c2d3
Revises: ad9080f8c23e
Create Date: 2026-05-28 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5b9f7a1c2d3"
down_revision: Union[str, None] = "ad9080f8c23e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qr_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("portal_type", sa.String(length=20), nullable=False),
        sa.Column("access_token", sa.String(length=511), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("qr_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_qr_sessions_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_qr_sessions_token"), ["token"], unique=True
        )

    op.create_table(
        "user_device_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=255), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_device_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_device_sessions_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_device_sessions_jti"), ["jti"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_device_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_device_sessions_jti"))
        batch_op.drop_index(batch_op.f("ix_user_device_sessions_id"))

    op.drop_table("user_device_sessions")
    with op.batch_alter_table("qr_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_qr_sessions_token"))
        batch_op.drop_index(batch_op.f("ix_qr_sessions_id"))

    op.drop_table("qr_sessions")
    # ### end Alembic commands ###
