"use client";

/**
 * FinWatch Zambia - Regulator FAQ Page
 */

import { useState } from "react";
import Link from "next/link";
import { ChevronDown, ChevronUp, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";

const FAQ_DATA = [
  {
    category: "Institutional Access",
    questions: [
      {
        q: "Who has access to the Regulator Portal?",
        a: "Access is restricted to authorized personnel from designated regulatory bodies in Zambia. Users are categorized as either 'Regulator' (full dashboard access) or 'Policy Analyst' (aggregate insights and reporting focus).",
      },
      {
        q: "How are invitation codes managed?",
        a: "Invitation codes are generated by system administrators and are unique to each institutional department. They ensure that only verified personnel can register for regulator-level accounts.",
      },
    ],
  },
  {
    category: "Data Methodology",
    questions: [
      {
        q: "How is SME data anonymized?",
        a: "We use a multi-layer anonymization protocol that strips all PII (Personally Identifiable Information) before data enters the institutional analytics engine. All metrics are aggregated at the sector level to ensure individual company privacy.",
      },
      {
        q: "Can I see the raw financial figures of a specific SME?",
        a: "No. The system is designed to prevent individual entity tracking. You can only see the statistical distributions and averages within a sector.",
      },
      {
        q: "What is the k-anonymity threshold?",
        a: "FinWatch requires at least 5 active companies in a sector before aggregate results are displayed. This prevents regulators from identifying entity status in very small or niche industries.",
      },
    ],
  },
  {
    category: "Analytical Logic",
    questions: [
      {
        q: "What triggers an anomaly flag?",
        a: "Anomalies are flagged based on statistical distance. The engine identifies records where financial ratios deviate significantly from the sector norm or exhibit internal mathematical inconsistencies.",
      },
      {
        q: "How often are the ML models updated?",
        a: "The core models (Random Forest and Logistic Regression) are trained on longitudinal data. We conduct periodic performance audits to ensure predictive accuracy remains high across current Zambian economic cycles.",
      },
    ],
  },
  {
    category: "Support and AI Assistant",
    questions: [
      {
        q: "What is the scope of the Institutional AI Assistant?",
        a: "The assistant is trained to help you interpret aggregate trends, explain detection logic, and guide you through the reporting features. It cannot provide individual company data or general economic forecasts.",
      },
      {
        q: "Are there limits on AI usage?",
        a: "Yes. To ensure equitable access and system stability, each institutional user has a rolling limit of 15 messages per 2-hour window for the Documentation AI Assistant, and 10 for the Portal AI Assistant.",
      },
    ],
  },
];

export default function RegulatorFAQPage() {
  const [openItems, setOpenItems] = useState<string[]>([]);

  const toggleItem = (q: string) => {
    setOpenItems((prev) =>
      prev.includes(q) ? prev.filter((item) => item !== q) : [...prev, q]
    );
  };

  return (
    <div className="container mx-auto max-w-4xl px-4 py-16 sm:px-6 text-left">
      {/* Breadcrumb */}
      <nav className="mb-8 flex items-center gap-2 text-sm text-muted-foreground">
        <Link
          href="/institutional/docs/regulator"
          className="hover:text-emerald-600 transition-colors"
        >
          Documentation
        </Link>
        <ChevronRight className="h-4 w-4" />
        <span className="font-medium text-foreground">FAQ</span>
      </nav>

      <div className="mb-16">
        <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl">
          Institutional <span className="text-emerald-600">FAQ</span>
        </h1>
        <p className="mt-4 text-lg text-muted-foreground">
          Quick answers to technical and procedural questions for regulatory
          users.
        </p>
      </div>

      <div className="space-y-12">
        {FAQ_DATA.map((cat, i) => (
          <div key={i} className="space-y-4">
            <h2 className="text-xl font-bold border-b border-border pb-2 text-zinc-900 dark:text-zinc-100">
              {cat.category}
            </h2>
            <div className="space-y-2">
              {cat.questions.map((item, j) => {
                const isOpen = openItems.includes(item.q);
                return (
                  <div
                    key={j}
                    className={cn(
                      "overflow-hidden rounded-xl border border-border transition-all",
                      isOpen
                        ? "bg-emerald-50/30 dark:bg-emerald-900/5 border-emerald-600/20"
                        : "bg-white dark:bg-zinc-950"
                    )}
                  >
                    <button
                      onClick={() => toggleItem(item.q)}
                      className="flex w-full items-center justify-between px-6 py-4 text-left transition-colors hover:bg-emerald-50 dark:hover:bg-emerald-900"
                    >
                      <span className="font-semibold text-zinc-900 dark:text-zinc-100">
                        {item.q}
                      </span>
                      {isOpen ? (
                        <ChevronUp className="h-5 w-5 text-emerald-600" />
                      ) : (
                        <ChevronDown className="h-5 w-5 text-muted-foreground" />
                      )}
                    </button>
                    {isOpen && (
                      <div className="px-6 pb-4 animate-in fade-in slide-in-from-top-1 duration-200">
                        <p className="text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
                          {item.a}
                        </p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-20 flex flex-col items-center justify-center rounded-3xl bg-zinc-50 p-8 text-center dark:bg-zinc-900/50">
        <h3 className="text-lg font-bold mb-2">Further Assistance</h3>
        <p className="text-sm text-muted-foreground mb-6">
          Authorized users can use the Institutional AI Assistant for specific
          system queries.
        </p>
        <Link
          href="/institutional/docs/regulator"
          className="text-sm font-bold text-emerald-600 hover:underline"
        >
          ← Back to Institutional Documentation
        </Link>
      </div>
    </div>
  );
}
